// Counter
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const INCREMENT_AQ_COUNTER = 'INCREMENT_AQ_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const DECREMENT_AQ_COUNTER = 'DECREMENT_AQ_COUNTER'

export const COUNT_AQ_RESPONSES = 'COUNT_AQ_RESPONSES'
